#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

# Normalize the url path syntax
path_url=$(ynh_normalize_url_path "$path_url")

# Check web path availability
ynh_webpath_available "$domain" "$path_url"
# Register (book) web path
ynh_webpath_register "$app" "$domain" "$path_url"

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set "$app" domain "$domain"
ynh_app_setting_set "$app" path "$path_url"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies php-openid

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_app_setting_set "$app" final_path "$final_path"
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source "$final_path" "app"
ynh_setup_source "$final_path/modules/openidProvider" "openidprovider"

mkdir "$final_path/tmp"

#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create $app

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

# Create a dedicated php-fpm config
ynh_add_fpm_config

#=================================================
# SPECIFIC SETUP
#=================================================
# Add a new LDAP source
#=================================================
# Apply modifications to upstream default
# TODO: reduce exposure of ldap attributes
cp ../conf/patches/config/authsources.php "$final_path/config/authsources.php"

touch $final_path/modules/ldap/enable

#=================================================
# Add a new LDAP source
#=================================================

# cf http://simplesamlphp.org/docs/stable/openidProvider:provider
cp ../conf/patches/config/module_openidProvider.php "$final_path/config/"
ynh_replace_string "__FINALPATH__" "$final_path"  "$final_path/config/module_openidProvider.php"

touch $final_path/modules/openidProvider/enable

#=================================================
# Create saml20-idp-hosted
#=================================================

# TODO : cert in saml20-idp-hosted.php ?
cp ../conf/patches/metadata/saml20-idp-hosted.php "$final_path/metadata/saml20-idp-hosted.php"

#=================================================
# Create config file
#=================================================

admin_pwd=$(ynh_string_random)
secret_salt=$(ynh_string_random)
contact_email="root@$domain"
config=$final_path/config/config.php

ynh_app_setting_set "$app" admin_pwd "$admin_pwd"
ynh_app_setting_set "$app" secret "$secret_salt"
ynh_app_setting_set "$app" contact_email "$secret_salt"

cp ../conf/patches/config/config.php "$config"

ynh_replace_string "__DOMAIN__"     "$domain"        "$config"
ynh_replace_string "__PATH__"       "$path_url"      "$config"
ynh_replace_string "__ADMIN_PWD__"  "$admin_pwd"     "$config"
ynh_replace_string "__SECRET__"     "$secret_salt"   "$config"
ynh_replace_string "__EMAIL__"      "$contact_email" "$config"
ynh_replace_string "__FINALPATH__"  "$final_path"    "$config"

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "$config"

#=================================================
# Init composer
#=================================================

init_composer "$final_path"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown -R root:root "$final_path"
chown -R "$app":"$app" "$final_path/tmp"

#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_delete "$app" skipped_uris

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
