#!/bin/bash -x

set -e

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a openidsimplesamlphp
if [[ ! $? -eq 0 ]]; then
  exit 1
fi

# This path is exposed in nginx
final_path_www=/var/www/simplesamlphp

# This path is not exposed.
# TODO: ideally this should be placed somewhere else, outside /var/www
final_path_lib=/var/www/simplesamlphp-lib

# Copy files to the right place
sudo mkdir -p $final_path_lib
sudo cp -ar ../sources/* $final_path_lib/
sudo mv $final_path_lib/www $final_path_www

# Apply modifications to upstream default
# TODO: reduce exposure of ldap attributes
sudo cp ../conf/patches/config/authsources.php $final_path_lib/config/authsources.php

sudo cp ../conf/patches/config/config.php $final_path_lib/config/config.php

admin_pwd=$(dd if=/dev/urandom bs=1 count=400 2> /dev/null | tr -c -d '[A-Za-z0-9]')
secret_salt=$(dd if=/dev/urandom bs=1 count=400 2> /dev/null | tr -c -d '[A-Za-z0-9]')
technical_contact_email="webmaster@$domain"
sudo sed -i "s,YNH_PATH,${path#?}/,g" $final_path_lib/config/config.php
sudo sed -i "s,YNH_ADMINPWD,$admin_pwd,g" $final_path_lib/config/config.php
sudo sed -i "s,YNH_SECRETSALT,$secret_salt,g" $final_path_lib/config/config.php
sudo sed -i "s,YNH_TECHNICAL_CONTACT_EMAIL,$technical_contact_email,g" $final_path_lib/config/config.php

# cf http://simplesamlphp.org/docs/stable/openidProvider:provider
sudo cp ../conf/patches/config/module_openidProvider.php $final_path_lib/config/

datadir=/home/yunohost.app/openidsimplesamlphp/openidfilestore
sudo mkdir -p $datadir
sudo chown -R www-data: $datadir

for f in $(find $final_path_lib/metadata  -maxdepth 1 -type f | grep -v saml20-idp-hosted)
do
    sudo cp ../conf/patches/metadata/empty.php $f
done
sudo cp ../conf/patches/metadata/saml20-idp-hosted.php $final_path_lib/metadata/saml20-idp-hosted.php
# TODO : cert in saml20-idp-hosted.php ?

sudo touch $final_path_lib/modules/ldap/enable
sudo touch $final_path_lib/modules/openidProvider/enable

sudo sed -i "s@dirname(dirname(__FILE__)) @'$final_path_lib'@g" $final_path_www/_include.php

sudo chown -R root:root $final_path_lib
sudo chown -R root:root $final_path_www

# Nginx config
# cf http://www.wogri.at/en/linux/openid-provider/
sudo sed -i "s@YNH_LOCATION@$path@g" ../conf/nginx.conf
sudo sed -i "s@YNH_PATH@$final_path_www@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/openidsimplesamlphp.conf

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app setting openidsimplesamlphp skipped_uris -v "/"
sudo yunohost app ssowatconf
