#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get "$app" domain)
path_url=$(ynh_app_setting_get "$app" path)
final_path=$(ynh_app_setting_get "$app" final_path)
admin_pwd=$(ynh_app_setting_get "$app" admin_pwd)
secret_salt=$(ynh_app_setting_get "$app" secret)
contact_email=$(ynh_app_setting_get "$app" contact_email)

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================

ynh_install_app_dependencies php-openid

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_app_setting_set "$app" final_path "$final_path"
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source "$final_path" "app"
ynh_setup_source "$final_path/modules/openidProvider" "openidprovider"

test -e "$final_path/tmp" || mkdir "$final_path/tmp"

#=================================================
# NGINX CONFIGURATION
#=================================================

# Create a dedicated nginx config
ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================

# Create a system user
ynh_system_user_create "$app"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================

# Create a dedicated php-fpm config
ynh_add_fpm_config

#=================================================
# SPECIFIC SETUP
#=================================================
# Add a new LDAP source
#=================================================
# Apply modifications to upstream default
# TODO: reduce exposure of ldap attributes
cp ../conf/patches/config/authsources.php "$final_path/config/authsources.php"

touch "$final_path/modules/ldap/enable"

#=================================================
# Add a new LDAP source
#=================================================

# cf http://simplesamlphp.org/docs/stable/openidProvider:provider
cp ../conf/patches/config/module_openidProvider.php "$final_path/config/"
ynh_replace_string "__FINALPATH__" "$final_path"  "$final_path/config/module_openidProvider.php"

touch "$final_path/modules/openidProvider/enable"

#=================================================
# Create saml20-idp-hosted
#=================================================

# TODO : cert in saml20-idp-hosted.php ?
cp ../conf/patches/metadata/saml20-idp-hosted.php "$final_path/metadata/saml20-idp-hosted.php"

#=================================================
# Create config file
#=================================================

config=$final_path/config/config.php

cp ../conf/patches/config/config.php "$config"

ynh_replace_string "__DOMAIN__"     "$domain"        "$config"
ynh_replace_string "__PATH__"       "$path_url"      "$config"
ynh_replace_string "__ADMIN_PWD__"  "$admin_pwd"     "$config"
ynh_replace_string "__SECRET__"     "$secret_salt"   "$config"
ynh_replace_string "__EMAIL__"      "$contact_email" "$config"
ynh_replace_string "__FINALPATH__"  "$final_path"    "$config"

#=================================================
# STORE THE CHECKSUM OF THE CONFIG FILE
#=================================================

# Calculate and store the config file checksum into the app settings
ynh_store_file_checksum "$config"

#=================================================
# Init composer
#=================================================

init_composer "$final_path"

#=================================================
# GENERIC FINALIZATION
#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown -R root:root "$final_path"
chown -R "$app":"$app" "$final_path/tmp"

#=================================================
# SETUP SSOWAT
#=================================================

ynh_app_setting_delete "$app" skipped_uris

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx
